# Generated by Django 3.2.9 on 2021-11-21 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_rename_job_seeker_job_seekers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_seekers',
            new_name='Student_user',
        ),
    ]
