# Generated by Django 3.2.9 on 2021-11-21 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_rename_job_seekers_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_user',
            new_name='Job_seeker',
        ),
    ]
