# Generated by Django 3.2.9 on 2021-11-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_role', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('salary', models.FloatField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('required_skills', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
            ],
        ),
    ]
